
task:
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-1
      pre_install_script:
        - pkg install -y libtool automake autoconf autoconf-archive gmake check pkgconfig libarchive
        - printf "#include <stdio.h>\nint main() { printf(\"hello-world\\\\n\"); return 0; }\n" > hello-world.c
        - clang -o hello-world hello-world.c
        - ./hello-world
    - osx_instance:
        image: catalina-xcode-12.0
      pre_install_script:
        - brew install libtool automake autoconf autoconf-archive check make pkgconfig libarchive
        - printf "#include <stdio.h>\nint main() { printf(\"hello-world\\\\n\"); return 0; }\n" > hello-world.c
        - clang -o hello-world hello-world.c
        - ./hello-world
      env:
        LDFLAGS: "-L/usr/local/opt/libarchive/lib"
        CPPFLAGS: "-I/usr/local/opt/libarchive/include"
        PKG_CONFIG_PATH: "/usr/local/opt/libarchive/lib/pkgconfig"
    - container:
        image: alpine:latest
      pre_install_script:
        - apk add clang autoconf automake automake make libtool check-dev libc-dev binutils gcc pkgconfig libarchive-dev
        - printf "#include <stdio.h>\nint main() { printf(\"hello-world\\\\n\"); return 0; }\n" > hello-world.c
        - clang -o hello-world hello-world.c
        - ./hello-world
      env:
          PKG_CONFIG_PATH:  /usr/share/aclocal

  install_script:
    - clang --version
    - ./autogen.sh
    - ./configure CC=clang || cat config.log
      # - gmake get-deps
  make_script:
    - make
  check_script: make check
  dist_check_script: make dist-check
  artifacts:
    - libcheck-*.tar.gz
    - libcheck-*.tar.xz
  always:
    test_artifacts:
      path: "test/*.log"
      type: text/plain
